### ISSUE TITLE
patch_data_prepare.py is killed after a few iterations

### ISSUE THREAD

**Issue by VitorGuizilini-TRI** [xinzhuma/patchnet#1]
Congratulations, these results are quite impressive. I am trying to replicate them using your pre-trained models, however I am having issues preparing the data, the process gets killed after a few iterations. Is there a way to not store everything in memory before pickling (or even better, using the data directly at training time)?

**Comment by xinzhuma** [comment]
It's necessary to process the data before training, which can speed up training and reduce computational overhead. I checked the script and it worked well. It will generate about 7.1G/1.7G/3.0  of training/validation/testing data. You can generate the testing data only if you just want use the pre-trained models. Besides, note that we also save the RGB value which is not used in subsequent steps (we save it for future work). You can delete it to save memory. If you want to do this, please modify the codes for **saving** and **reading** in  **patchnet_data_prepare.py** and **patchnet_dataset.py** accordingly.

**Comment by xinzhuma** [comment]
It's necessary to process the data before training, which can speed up training and reduce computational overhead. I checked the script and it worked well. It will generate about 7.1G/1.7G/3.0 of training/validation/testing data. You can generate the testing data only if you just want use the pre-trained models. Besides, note that we also save the RGB value which is not used in subsequent steps (we save it for future work). You can delete it to save memory. If you want to do this, please modify the codes for **saving** and **reading** operations in **patchnet_data_prepare.py** and **patchnet_dataset.py** accordingly.

**Comment by xinzhuma** [comment]
> Congratulations, these results are quite impressive. I am trying to replicate them using your pre-trained models, however I am having issues preparing the data, the process gets killed after a few iterations. Is there a way to not store everything in memory before pickling (or even better, using the data directly at training time)?

It's necessary to process the data before training, which can speed up training and reduce computational overhead. I checked the script and it worked well. It will generate about 7.1G/1.7G/3.0G of training/validation/testing data. You can generate the testing data only if you just want use the pre-trained models. Besides, note that we also save the RGB value which is not used in subsequent steps (we save it for future work). You can delete it to save memory. If you want to do this, please modify the codes for **saving** and **reading** operations in **patchnet_data_prepare.py** and **patchnet_dataset.py** accordingly.

**Comment by VitorGuizilini-TRI** [comment]
Thank you, it's working now. Another related question: how do I prepare the test data?

**Comment by VitorGuizilini-TRI** [comment]
Nevermind, it's working now.

**Comment by xinzhuma** [comment]
> Thank you, it's working now. Another related question: how do I prepare the test data?

To prepare test data, you need to:
- prepare 2d detection results 
- modify the **'split'** in data prepare script (Line 337-352). Make sure the training set is **'tranval'**, and testing set is **'test'**.
