### ISSUE TITLE
box2d

### ISSUE THREAD

**Issue by pengweiweiwei** [xinzhuma/patchnet#12]
你好，想请问下您的代码里面patch的获取是不是直接利用了2d框的GT，这样的话相当于2d检测百分之百正确了

**Comment by xinzhuma** [comment]
> 你好，想请问下您的代码里面patch的获取是不是直接利用了2d框的GT，这样的话相当于2d检测百分之百正确了

不是GT, 使用了额外的一个2D检测器的输出结果。具体可以参考：Frustum PointNets for 3D Object Detection from RGB-D Data, CVPR'2018

**Comment by pengweiweiwei** [comment]
好的，谢谢解答

**Comment by wanyanchen** [comment]
您好，我跑了一下您的代码，发现训练的时候patch好像确实是2d box gt 得到的，只不过做了一些增广，而infer的时候 patch是通过额外的2D检测器得到的。
当我把infer 时候的2d box换成gt时，得到3d box 性能指标大幅度下降，这个现象很奇怪，请问您有遇到过这种情况么

**Comment by xinzhuma** [comment]
> 您好，我跑了一下您的代码，发现训练的时候patch好像确实是2d box gt 得到的，只不过做了一些增广，而infer的时候 patch是通过额外的2D检测器得到的。
> 当我把infer 时候的2d box换成gt时，得到3d box 性能指标大幅度下降，这个现象很奇怪，请问您有遇到过这种情况么

1. 是的， 使用GT训练，额外的2d detector测试。
2. inference如果使用GT 2d bbox的话，无法确定每个3d bbox的score，会被直接置为1。而在使用2D bbox的话，可以将2D bbox的score直接用作3D bbox score。这是产生性能差异的主要原因。

**Comment by wanyanchen** [comment]
就是说，kitti eval的时候3d box score这个指标很重要，如果都是1就会性能下降很多是么

**Comment by xinzhuma** [comment]
> 就是说，kitti eval的时候3d box score这个指标很重要，如果都是1就会性能下降很多是么

是的。理想状态下需要将估计的准的box的score尽可能的高。

**Comment by wanyanchen** [comment]
好的，谢谢啦
