### ISSUE TITLE
关于fpoinnet和pseudo-lidar

### ISSUE THREAD

**Issue by evil-master** [xinzhuma/patchnet#13]
请问当我用fpointnet和pseudo-lidar的数据预处理去生成3个pickle文件时，_val_rgb_detection.pickle文件总是为空,请问是什么原因呢?我该怎么做去生成此文件.

**Comment by xinzhuma** [comment]
> 请问当我用fpointnet和pseudo-lidar的数据预处理去生成3个pickle文件时，_val_rgb_detection.pickle文件总是为空,请问是什么原因呢?我该怎么做去生成此文件.

我这边没有发现这个问题，能否确认数据/路径等配置完全正确？
如果依旧存在这个问题，可以将log发到xinzhu.ma@sydney.edu.au，我会再检查一下

**Comment by jingangchen34** [comment]
![2021-03-17 20-49-25屏幕截图](https://user-images.githubusercontent.com/57422743/111470017-5787e280-8762-11eb-9943-6e33efb2d7d6.png)

**Comment by jingangchen34** [comment]
> > 请问当我用fpointnet和pseudo-lidar的数据预处理去生成3个pickle文件时，_val_rgb_detection.pickle文件总是为空,请问是什么原因呢?我该怎么做去生成此文件.
> 
> 我这边没有发现这个问题，能否确认数据/路径等配置完全正确？
> 如果依旧存在这个问题，可以将log发到[xinzhu.ma@sydney.edu.au](mailto:xinzhu.ma@sydney.edu.au)，我会再检查一下
只有ｐａｔｃｈｎｅｔ是正常的，但是fpointnet和pseudo-lidar总是不行
