### ISSUE TITLE
Can PatchNet be used to do distance measurement?

### ISSUE THREAD

**Issue by CaptainEven** [xinzhuma/patchnet#14]

**Comment by xinzhuma** [comment]
About this question, If I understand correctly, the performance of patchnet can be regarded as an auxiliary metric for the depth estimation task.  Please refer to 'Wasserstein Distances for Stereo Disparity Estimation, neurips2020'.

**Comment by CaptainEven** [comment]
@xinzhuma Thanks for your quick reply. I'll  dig into the paper and code for more details.
