### ISSUE TITLE
Question regarding lib/models/patchnet.py

### ISSUE THREAD

**Issue by quang-truong** [xinzhuma/patchnet#17]
May I know the purpose of the operations on lines 67, 74, and 90? I don't understand why patch values are deducted by mean value and later adding mean value back to center to get stage1_center. Thank you very much in advance.

**Comment by xinzhuma** [comment]
> May I know the purpose of the operations on lines 67, 74, and 90? I don't understand why patch values are deducted by mean value and later adding mean value back to center to get stage1_center. Thank you very much in advance.

For the coordinate system transformation. There is a visualization for this in Fig.4 of the paper [1]

[1] Frustum PointNets for 3D Object Detection from RGB-D Data, Charles et al., CVPR'18

**Comment by quang-truong** [comment]
Thank you.
