### ISSUE TITLE
Visualization tools

### ISSUE THREAD

**Issue by SlingHe** [xinzhuma/patchnet#2]
Can you provide a script or toolbox that you use to visualize 3d bbox on monocular images and lidar scans? Thanks a lot.

**Comment by xinzhuma** [comment]
OK, I added a simple script for visualization in **root/tools** directory. You can try it now.

**Comment by xinzhuma** [comment]
> Can you provide a script or toolbox that you use to visualize 3d bbox on monocular images and lidar scans? Thanks a lot.

OK, I added a simple script for visualization in **root/tools directory**. You can try it now.
