### ISSUE TITLE
Questions about the KITTI datasets

### ISSUE THREAD

**Issue by BitandPoly** [xinzhuma/patchnet#22]
Hello @xinzhuma, thanks for your wonderful contribution.  I have two questions about KITTI datasets. I would be appreciated if you can give me some help:

1. I didn't find the '2d_detections' on the KITTI website. Does '2d_detections' match to 'Download reference detections (L-SVM) for training and test set (800 MB)' in KITTI? 

2. I also didn't find 'ImageSets', could you please tell me which file I need to download and put it in this file? 

Thanks in advance.

**Comment by xinzhuma** [comment]
1. '2D detections' is the 2D bounding boxes predicted by a self-trained models. We provide these results on train/val set [data/KITTI/2d_detections], while you need to prepare the test set results by yourself if you want get the test set 3D detections.
2.  we provide these files in this repo [data/KITTI/Image_Sets]

**Comment by BitandPoly** [comment]
Sorry for the late reply. Thanks a lot again for your great contribution!
