### ISSUE TITLE
CAN'T inference use your pretrain models

### ISSUE THREAD

**Issue by PengfeiMa** [xinzhuma/patchnet#4]
Hi, @xinzhuma when I use your pretrain models for evaluate. I meet the screenshot error.
I change the 'lib/helper/model_builder.py' line 4: ` from lib.models.patchnet_vanilla import PatchNet_Vanilla` to `from lib.models.patchnet import PatchNet`. If I should't change this, could you share me your 'patchnet_vanilla.py' OR a 'patchnet' model?
SO：
1. Is there any configs that I should modify?
2. or I can't use your models directly.

![image](https://user-images.githubusercontent.com/20807385/91009786-e17c2c80-e613-11ea-92e7-e91b2ff32db6.png)

**Comment by PengfeiMa** [comment]
the ERROR detail:
2020-08-24 06:02:25,694   INFO  Load data from ../../data/KITTI/pickle_files/patch_carpedcyc_val.pickle
2020-08-24 06:02:29,847   INFO  ==> Loading from checkpoint '/workspace/patchnet/checkpoints/checkpoint_patchnet_stereo.pth'
Traceback (most recent call last):
  File "../../tools/train_val.py", line 101, in <module>
    main()
  File "../../tools/train_val.py", line 77, in main
    tester.test()
  File "/workspace/patchnet/lib/helpers/tester_helper.py", line 27, in test
    logger=self.logger)
  File "/workspace/patchnet/lib/helpers/save_helper.py", line 31, in load_checkpoint
    model.load_state_dict(checkpoint['model_state'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PatchNet:
        Unexpected key(s) in state_dict: "box_est_backbone.layer1.0.fc1.weight", "box_est_backbone.layer1.0.fc1.bias", "box_est_backbone.layer1.0.fc2.weight", "box_est_backbone.layer1.0.fc2.bias", "box_est_backbone.layer1.1.fc1.weight", "box_est_backbone.layer1.1.fc1.bias", "box_est_backbone.layer1.1.fc2.weight", "box_est_backbone.layer1.1.fc2.bias", "box_est_backbone.layer2.0.fc1.weight", "box_est_backbone.layer2.0.fc1.bias", "box_est_backbone.layer2.0.fc2.weight", "box_est_backbone.layer2.0.fc2.bias", "box_est_backbone.layer2.1.fc1.weight", "box_est_backbone.layer2.1.fc1.bias", "box_est_backbone.layer2.1.fc2.weight", "box_est_backbone.layer2.1.fc2.bias", "box_est_backbone.layer3.0.fc1.weight", "box_est_backbone.layer3.0.fc1.bias", "box_est_backbone.layer3.0.fc2.weight", "box_est_backbone.layer3.0.fc2.bias", "box_est_backbone.layer3.1.fc1.weight", "box_est_backbone.layer3.1.fc1.bias", "box_est_backbone.layer3.1.fc2.weight", "box_est_backbone.layer3.1.fc2.bias", "box_est_backbone.layer4.0.fc1.weight", "box_est_backbone.layer4.0.fc1.bias", "box_est_backbone.layer4.0.fc2.weight", "box_est_backbone.layer4.0.fc2.bias", "box_est_backbone.layer4.1.fc1.weight", "box_est_backbone.layer4.1.fc1.bias", "box_est_backbone.layer4.1.fc2.weight", "box_est_backbone.layer4.1.fc2.bias".
        size mismatch for box_est_backbone.conv1.weight: copying a param with shape torch.Size([64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 3, 1, 1]).
        size mismatch for box_est_backbone.layer1.0.conv2.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 2, 3, 3]).
        size mismatch for box_est_backbone.layer1.1.conv2.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 2, 3, 3]).
        size mismatch for box_est_backbone.layer2.0.conv2.weight: copying a param with shape torch.Size([128, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 4, 3, 3]).
        size mismatch for box_est_backbone.layer2.1.conv2.weight: copying a param with shape torch.Size([128, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 4, 3, 3]).
        size mismatch for box_est_backbone.layer3.0.conv2.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 8, 3, 3]).
        size mismatch for box_est_backbone.layer3.1.conv2.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 8, 3, 3]).
        size mismatch for box_est_backbone.layer4.0.conv2.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 16, 3, 3]).
        size mismatch for box_est_backbone.layer4.1.conv2.weight: copying a param with shape torch.Size([512, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 16, 3, 3]).

**Comment by xinzhuma** [comment]
Just delete the code related to 'patchnet-vanilla' and 'am3d' in 'lib/helper/model_builder.py'.  Besides, this error caused by the mismatch between pre-trained model and config file. The pre-trained model use 'senet' as backbone while that in the default config is 'resnext'. Sorry for that. Please modify the config to fix it.

**Comment by xinzhuma** [comment]
> Hi, @xinzhuma when I use your pretrain models for evaluate. I meet the screenshot error.
> I change the 'lib/helper/model_builder.py' line 4: ` from lib.models.patchnet_vanilla import PatchNet_Vanilla` to `from lib.models.patchnet import PatchNet`. If I should't change this, could you share me your 'patchnet_vanilla.py' OR a 'patchnet' model?
> SO：
> 
> 1. Is there any configs that I should modify?
> 2. or I can't use your models directly.
> 
> ![image](https://user-images.githubusercontent.com/20807385/91009786-e17c2c80-e613-11ea-92e7-e91b2ff32db6.png)

Just delete the code related to 'patchnet-vanilla' and 'am3d' in 'lib/helper/model_builder.py'. Besides, this error caused by the mismatch between pre-trained model and config file. The pre-trained model use 'senet' as backbone while that in the default config is 'resnext'. Sorry for that. Please modify the config to fix it.

**Comment by PengfeiMa** [comment]
Thank you for your reply! :)   @xinzhuma 
The above questions is solved, but another happened ! Any suggestions?

  File "../../tools/train_val.py", line 101, in <module>
    main()
  File "../../tools/train_val.py", line 77, in main
    tester.test()
  File "/workspace/patchnet/lib/helpers/tester_helper.py", line 28, in test
    self.test_one_epoch()
  File "/workspace/patchnet/lib/helpers/tester_helper.py", line 47, in test_one_epoch
    for _, data in enumerate(self.dataloader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/workspace/patchnet/lib/datasets/patch_dataset.py", line 67, in __getitem__
    patch[:, :, 0:3] = self.rotato_patch_to_center(patch[:, :, 0:3], rot_angle)
TypeError: string indices must be integers

eval:   0%|                                                                                                                                                                                                           | 0/219 [00:00<?, ?it/s]

**Comment by xinzhuma** [comment]
> patch[:, :, 0:3] =

it seems something wrong when you generate the training/testing data? can you share more information about it?

**Comment by PengfeiMa** [comment]
Thank you for your great job! 
It works! 👍

**Comment by PengfeiMa** [comment]
Hi, @xinzhuma,  I evaluate the mono model on the val data. The car's mAP is the same as yours, but ped and cyc are '0'.
Have you trained ped and cyc in your mono release model?

**Comment by xinzhuma** [comment]
> Hi, @xinzhuma, I evaluate the mono model on the val data. The car's mAP is the same as yours, but ped and cyc are '0'.
> Have you trained ped and cyc in your mono release model?

The pre-trained model is only trained from the car instance.

**Comment by PengfeiMa** [comment]
OK, 3Q 👍
