### ISSUE TITLE
Performance of provided FPointNet

### ISSUE THREAD

**Issue by gujiaqivadin** [xinzhuma/patchnet#5]
Hello, xinzhuma.
      Thanks for your great work of patchnet. I noticed that you also provide your realization of FPointnet and PseudoLiDAR in your repository. And I try to run both of two only for test. The results of FPointNet are a little different from official code of FPointNet.
Did you test your realization of FPointNet, and can you give your results on KITTI val set for reference? Thanks a lot.

**Comment by xinzhuma** [comment]
The default setting in provided codes is different from that in FPointNet's official repo, especially for the training schedule. We use some different hyper-params for faster convergence. For pseudo-LiDAR, it can accelerate training and get the same or better results, while the performance of FPointNet is slightly reduced. If you want to reproduce the performance reported in the FPointNet paper, you can try to adjust the training schedule.
