### ISSUE TITLE
Unable to convergence

### ISSUE THREAD

**Issue by xdhuang493** [xinzhuma/patchnet#6]
hi, when i train according to your steps. Why does the loss go up with the epoch increase (in one epoch the loss is decreasing), the first epoch ,The loss converges to 22 , but the last few epochs ,loss converges to 100+.How can I solve this problem?

**Comment by xinzhuma** [comment]
> i, when i train according to your steps. Why does the loss go up with the epoch increase (in one epoch the loss is decreasing), the first epoch ,The loss converges to 22 , but the last few epochs ,loss converges to 100+.How can I solve this problem?

Can you provide more details? I need more information to check it.

**Comment by xdhuang493** [comment]
> i, when i train according to your steps. Why does the loss go up with the epoch increase (in one epoch the loss is decreasing), the first epoch ,The loss converges to 22 , but the last few epochs ,loss converges to 100+.How can I solve this problem?
> 
> Can you provide more details? I need more information to check it.

i use Monocular depth ,then run the patch_data_prepare.py to generate train,val data cars only.final i run the train_val.py without changing the .yaml(only change the  file path and workers)

**Comment by xinzhuma** [comment]
@xdhuang493   I checked the monocular model and I didn't observe the problem you mentioned. The loss is about 22 in the fist epoch, but is still decreases during the training. If this problem still exists in your environment, you can send the config&log files to my email xima0693@uni.sydney.edu.au, I will check it again.
