### ISSUE TITLE
the performance of pretrained model

### ISSUE THREAD

**Issue by felixchengxh** [xinzhuma/patchnet#7]
Hi, @xinzhuma .
Thank you for providing the impressive work of patchnet. When I try to evaluate the pretrained model, the results didn't reach the goals that you provided on your github page. I changed the path in' experiments/patchnet/config_patchnet.yaml': resume_model: 'checkpoints/checkpoint_patchnet_mono.pth'. And I've prepared the data 'data/KITTI/object/training/label_2' before, but still got poor performances. (34.3/19.1/16.1)
Are there anything else I should check to reach the results as shown? Thank you!

**Comment by xinzhuma** [comment]
> Hi, @xinzhuma .
> Thank you for providing the impressive work of patchnet. When I try to evaluate the pretrained model, the results didn't reach the goals that you provided on your github page. I changed the path in' experiments/patchnet/config_patchnet.yaml': resume_model: 'checkpoints/checkpoint_patchnet_mono.pth'. And I've prepared the data 'data/KITTI/object/training/label_2' before, but still got poor performances. (34.3/19.1/16.1)
> Are there anything else I should check to reach the results as shown? Thank you!

If you cannot get the same performances as described in Github using the provided pre-trained models. This may be something wrong with your testing data. Please check data generation related steps and try again. If there are still some problems, you can send me the config&log files and I will check it again.
