### ISSUE TITLE
One Question abou rotato_patch_to_center

### ISSUE THREAD

**Issue by Cknex** [xinzhuma/patchnet#8]
您好！我发现您读取数据时，对每一个物体框的x,z通道调用了rotato_patch_to_center这个函数，请问这个函数是做什么的呢？ 非常感谢！

**Comment by xinzhuma** [comment]
> 您好！我发现您读取数据时，对每一个物体框的x,z通道调用了rotato_patch_to_center这个函数，请问这个函数是做什么的呢？ 非常感谢！

这个工作是通过是一个pseudo-lidar的图像形式等价版本来探究pseudo-lidar能够work的原因，我们选取了基于fpointnet的pseudo-lidar版本来探究这个问题。你提到的这个操作源自fpointnet，其意图在于将坐标系中心移至目标中心，这样有助于后续步骤。具体细节请参考：https://openaccess.thecvf.com/content_cvpr_2018/html/Qi_Frustum_PointNets_for_CVPR_2018_paper.html (figure.4).

**Comment by Cknex** [comment]
非常感谢！！
